# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: jedisolomon/curl-jq:latest

variables:
#API RETRIEVAL FROM CCP
#  AppID: 'WebServiceTest'
#  Safe: 'changemeapp'
#  ObjectName: 'clientnode1'
#  PVWA_URL: https://192.168.148.15/AIMWebService/api/Accounts?AppID=$AppID&Safe=$Safe&Folder=Root&Object=$ObjectName
  
#  CONJUR_AUTHN_URL: https://$CONJUR_APPLIANCE_URL/authn/dev/host%2f$CONJUR_HOST/authenticate
#  CONJUR_GET_PASSWORD_URL: https://$CONJUR_APPLIANCE_URL/secrets/dev/variable/$SECRET
#  CONJUR_UPDATE_POLICY_URL: https://$CONJUR_APPLIANCE_URL/policies/dev/policy/root/

#  CONTENT_JSON: 'Content-Type: application/json'
#  CONTENT_PLAIN: 'Content-Type: test/plain'
#  AUTHORIZATION: 'Authorization: Token token='
  QUOTE: '"'

before_script:
#  - APIKEY=$(curl -ks GET "${PVWA_URL}" -H "${CONTENT}" | jq -r .Content)
#  - AUTHN=$(curl -kv POST "${CONJUR_AUTHN_URL}" -H "${CONTENT_PLAIN}" --data "$CONJUR_APIKEY")
#  - AUTHTOKEN=$(echo "${AUTHN}" | base64 -w 0)
#  - UPDATE_POLICY=$(curl -ks GET "${CONJUR_UPDATE_POLICY_URL}" -H "${AUTHORIZATION}${QUOTE}${AUTHTOKEN}${QUOTE}" --data "${POLICY}")
#  - PASS=$(curl -ks GET "${CONJUR_GET_PASSWORD_URL}" -H "${AUTHORIZATION}${QUOTE}${AUTHTOKEN}${QUOTE}") 

get_password:
  stage: build
  only:
    - master
  script:
  - echo ${POLICY_LIST}
  - bash policy.sh $CONJUR_HOST $CONJUR_APIKEY 'dev' $CONJUR_APPLIANCE_URL
